/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.yofik.observe.the.sun;

public class App {
    public String getGreeting() {
        return "Hello World! Observe the Sun";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
